# ndarray

In [1]:
arr = [1,2,3]

print(arr*5)

arr = [x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr1 = arr1*5
print(arr1)

[ 5 10 15]


# Ndarray

In [42]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5])

print(type(arr1))
print(arr1.ndim)

# 2D array
arr2 = np.array([[1,2,3], # Row1
                [4,5,6]   # Row2
                ])
print(arr2.ndim)

# 3D array
arr3 = np.array([
        # 1st floor
        [[1,2,3], # Row1
        [4,5,6] ],   # Row2
        # 2nd floor 
        [[1,2,3], # Row1
        [4,5,6] ]   # Row2
    
])
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


## Array attributes

In [43]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
# shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
# data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
# size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12


# nd array data type

In [5]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.3])

print(arr.dtype)



int64
float64


In [6]:
arr = np.array([1,2,3.3])
# upcasting
print(arr.dtype)
# upcasting to string
arr = np.array([1,2,3.3,'3'])
print(arr.dtype)

float64
<U32


## selecting a data type for an array

In [7]:
arr = np.array([1,2,3])
print(arr.dtype)
arr = arr.astype(np.int32)
print(arr.dtype)
print(arr)

int64
int32
[1 2 3]


# nd array creating from existing data

In [8]:
# List
lst = [10,20,30,40,40.5]
arr = np.array(lst,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

matrix = [[1,2,3], # Row1
         [4,5,6]   # Row2
                ]
arr = np.array(matrix,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
(2, 3)
2


In [9]:
# tuple
tpl=(10,20,30)
arr = np.array(tpl,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int32
(3,)
1


In [10]:
# set

st = {1,2,3}
arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [11]:
# dictonary
dc = {'a' : 10,'b' : 20, 'c':30}

keys = dc.keys()
values = dc.values()
items = dc.items()
print(items)

# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [12]:
# values to ndarray
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
3


In [13]:
# items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# array creation of random value

In [19]:
## np.random.rand(shape)

arr = np.random.rand(2,3) # 0 -> 1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.16598466 0.72998926 0.95401635]
 [0.43707434 0.1110849  0.46598209]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [20]:
## np.random.randint(start,end,shape)

arr = np.random.randint(1,10,(10,10)) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[4 2 6 8 4 3 4 4 5 6]
 [8 9 5 7 9 7 7 7 1 2]
 [7 9 6 8 3 3 9 3 5 6]
 [6 9 6 8 7 7 9 8 9 4]
 [4 3 9 3 5 3 9 5 9 8]
 [4 7 5 6 3 5 3 6 2 6]
 [6 3 1 8 5 5 3 7 6 7]
 [2 9 7 6 2 5 5 2 2 8]
 [6 6 5 2 2 4 4 1 2 9]
 [4 3 8 9 1 8 6 8 4 6]]
<class 'numpy.ndarray'>
int32
(10, 10)
2
100


In [23]:
## np.random.uniform(start,end,shape)

arr = np.random.uniform(50,100,(3,3,4)) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[68.35182425 67.92204237 78.28265399 57.7146814 ]
  [56.03015893 73.15462416 93.8252858  91.85969816]
  [77.53768436 87.66549353 58.37493152 65.56381155]]

 [[51.47955452 59.19529268 75.95798581 73.01145028]
  [54.01220701 61.58626839 63.02978794 95.96749162]
  [51.88773398 69.6145512  53.30959536 53.23827846]]

 [[70.28879276 59.46420691 66.03424098 78.20729889]
  [77.03196727 92.36437809 64.4778071  68.95415124]
  [71.23324212 54.03833468 67.6702404  90.05005474]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


# array creation with range

In [25]:
# np.arange(first,end,step) > similar to range function

arr = np.arange(1,10,1).reshape(3,3)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [28]:
# np.linspace(start,end,koita value)

arr = np.linspace(1,10,10)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
float64
(10,)
1
10


In [31]:
# np.logspace(start,end,koita value)

arr = np.logspace(0,4,6,base=2)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


# indexing and slicing

In [34]:
# indexing

print(arr1)
print(arr2)

# 1d array indexing
print(arr1[2])

# 2d array indexing
print(arr2[0][2])

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
3
3


In [35]:
# slicing
# 1d = arr[start:end:step]

arr1_mod=arr1[1:4]
print(arr1_mod)

[2 3 4]


In [41]:
# 2d array slicing
#arr[row_start:row_end:step, column_start:column_end:step]

print(arr2)

# getting a row
row_0=arr2[0:1,]
print(row_0)

# geting a column
col_0=arr2[::,0:1]
print(col_0)

[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[[1]
 [4]]


# practice problem solve

In [1]:
# 1. You have a list of temperatures recorded in Celsius. Your task is to:
#Create a NumPy array from the given list.
#Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
#Print the new Fahrenheit array.

import numpy as np
celsius_list =[10,20,30,40,50,60]
celcius_array = np.array(celsius_list)
farenheit_array = celcius_array * 1.8 + 32
print(farenheit_array)


[ 50.  68.  86. 104. 122. 140.]


In [3]:
# 2.  You have a Python list containing the lap times (in seconds) for an athlete.

#Task:
#Convert the list into a NumPy array.
#Print the array's shape, size, and data type.
#The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
#Print the new array of lap times in minutes.

lap_times = [60, 62, 58, 65, 70]

lap_array = np.array(lap_times)

print("Shape:", lap_array.shape)
print("Size:", lap_array.size)
print("Data type:", lap_array.dtype)

lap_minit = lap_array / 60

print("Lap times in minutes:", lap_minit)

Shape: (5,)
Size: 5
Data type: int64
Lap times in minutes: [1.         1.03333333 0.96666667 1.08333333 1.16666667]


In [4]:
# test