# numpy array manupulation

In [1]:
import numpy as np

arr = np.random.randint(1,100, size =(10,5)) #sample -10 , feature - 5
arr.shape


(10, 5)

In [2]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[65, 43, 86, 96, 24, 62, 64, 82, 49, 80],
       [ 9, 43, 47, 58, 98, 19, 94, 93, 88, 14],
       [60, 71, 49, 57, 40, 58,  6, 74, 56, 13],
       [ 8, 64,  4, 98, 57, 73, 38, 66, 65, 90],
       [25,  2, 35,  8, 25, 41, 79, 26, 69, 83]], dtype=int32)

In [3]:
flatten = b.flatten()

print(flatten.ndim)
flatten

column_wise_flattening=np.ravel(b,order='F') # row wise er jonno order='C' use korte hbe
print(column_wise_flattening)

1
[65  9 60  8 25 43 43 71 64  2 86 47 49  4 35 96 58 57 98  8 24 98 40 57
 25 62 19 58 73 41 64 94  6 38 79 82 93 74 66 26 49 88 56 65 69 80 14 13
 90 83]


In [4]:
a = np.random.randint(1,10, size =(2,3))
b = np.random.randint(20,30, size =(2,3))

print(a)
print(b)

[[4 6 9]
 [2 9 1]]
[[27 20 23]
 [22 23 25]]


## concatanate

In [5]:
con_row = np.concatenate((a,b),axis=0) # row_wise = 0
print(con_row)
con_col = np.concatenate((a,b),axis=1) # column_wise = 1
print(con_col)
# row wise concatanate korar somoye column same thakte hbe
# col wise concatenate korar  somoye row same thakte hbe

[[ 4  6  9]
 [ 2  9  1]
 [27 20 23]
 [22 23 25]]
[[ 4  6  9 27 20 23]
 [ 2  9  1 22 23 25]]


## transpose

In [6]:
mat = np.array([[10,20,30],
                [40,50,60]
                ])
transpose = mat.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [7]:
# array split
a = np.random.randint(1,10, size =(10,))
print(a)
splitted_array = np.array_split(a,3)
print(splitted_array)

# split -> equal division

[4 9 3 7 9 9 4 1 7 4]
[array([4, 9, 3, 7], dtype=int32), array([9, 9, 4], dtype=int32), array([1, 7, 4], dtype=int32)]


# arithmatic  operator and mathmatical function

In [8]:
# faster for vectorization

x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add=np.add(x,y)
print(add)

sub=x-y
print(sub)

mul=x*y
print(mul)

div=x/y
print(div)

reminder=x%y
print(reminder)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [9]:
# mathmatical function

# trigronometri funtion
# sin,cos tan takes value radian

sin_val=np.sin(x)
print(sin_val)

deg_con=np.rad2deg(x)
print(deg_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


# logical function

In [10]:
# comparison operator - .>, >, >=, =<, ==, !=

x = np.array([10,20,30,40])
y = np.array([2,3,30,5])

greater = x>y
print(greater)
equal = x==y
print(equal)

# all() -> shob true kina
# any() -> jekono ekta true kina

print(np.all(greater))
print(np.any(equal))


[ True  True False  True]
[False False  True False]
False
True
