# numpy array manupulation

In [1]:
import numpy as np

arr = np.random.randint(1,100, size =(10,5)) #sample -10 , feature - 5
arr.shape


(10, 5)

In [11]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[85, 27, 29, 33, 84, 38, 78, 86, 29, 20],
       [13, 62, 58, 45, 20, 55, 12,  7, 59, 57],
       [96, 22, 94, 71, 17,  9, 55, 38, 12, 68],
       [88, 38, 23, 26, 59,  9, 81, 97, 17, 56],
       [73, 46, 87, 63, 80, 78, 98, 79, 89, 79]], dtype=int32)

In [12]:
flatten = b.flatten()

print(flatten.ndim)
flatten

column_wise_flattening=np.ravel(b,order='F') # row wise er jonno order='C' use korte hbe
print(column_wise_flattening)

1
[85 13 96 88 73 27 62 22 38 46 29 58 94 23 87 33 45 71 26 63 84 20 17 59
 80 38 55  9  9 78 78 12 55 81 98 86  7 38 97 79 29 59 12 17 89 20 57 68
 56 79]


In [13]:
a = np.random.randint(1,10, size =(2,3))
b = np.random.randint(20,30, size =(2,3))

print(a)
print(b)

[[8 7 2]
 [3 1 1]]
[[23 20 29]
 [27 29 26]]


## concatanate

In [17]:
con_row = np.concatenate((a,b),axis=0) # row_wise = 0

print(con_row)
con_col = np.concatenate((a,b),axis=1) # column_wise = 1
print(con_col)

# row wise concatanate korar somoye column same thakte hbe
# col wise concatenate korar  somoye row same thakte hbe

[[ 8  7  2]
 [ 3  1  1]
 [23 20 29]
 [27 29 26]]
[[ 8  7  2 23 20 29]
 [ 3  1  1 27 29 26]]


## transpose

In [18]:
mat = np.array([[10,20,30],
                [40,50,60]
                ])
transpose = mat.T

print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [21]:
# array split
a = np.random.randint(1,10, size =(10,))
print(a)
splitted_array = np.array_split(a,3)
print(splitted_array)

# split -> equal division

[6 6 2 6 8 7 8 2 9 6]
[array([6, 6, 2, 6], dtype=int32), array([8, 7, 8], dtype=int32), array([2, 9, 6], dtype=int32)]
