# numpy array manupulation

In [22]:
import numpy as np

arr = np.random.randint(1,100, size =(10,5)) #sample -10 , feature - 5
arr.shape


(10, 5)

In [23]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[45, 39, 61, 34, 67, 25, 17, 43, 18, 76],
       [13, 87,  5, 31, 83, 13, 16, 19, 34, 26],
       [72, 91, 30, 98, 66, 75, 23, 36, 68, 87],
       [65, 61,  1, 31, 13,  5, 31, 34, 46, 39],
       [61, 87, 40,  1, 57, 93, 20, 18, 45, 43]], dtype=int32)

In [24]:
flatten = b.flatten()

print(flatten.ndim)
flatten

column_wise_flattening=np.ravel(b,order='F') # row wise er jonno order='C' use korte hbe
print(column_wise_flattening)

1
[45 13 72 65 61 39 87 91 61 87 61  5 30  1 40 34 31 98 31  1 67 83 66 13
 57 25 13 75  5 93 17 16 23 31 20 43 19 36 34 18 18 34 68 46 45 76 26 87
 39 43]


In [25]:
a = np.random.randint(1,10, size =(2,3))
b = np.random.randint(20,30, size =(2,3))

print(a)
print(b)

[[7 4 5]
 [4 4 6]]
[[22 22 23]
 [21 25 25]]


## concatanate

In [26]:
con_row = np.concatenate((a,b),axis=0) # row_wise = 0

print(con_row)
con_col = np.concatenate((a,b),axis=1) # column_wise = 1
print(con_col)

# row wise concatanate korar somoye column same thakte hbe
# col wise concatenate korar  somoye row same thakte hbe

[[ 7  4  5]
 [ 4  4  6]
 [22 22 23]
 [21 25 25]]
[[ 7  4  5 22 22 23]
 [ 4  4  6 21 25 25]]


## transpose

In [27]:
mat = np.array([[10,20,30],
                [40,50,60]
                ])
transpose = mat.T

print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [28]:
# array split
a = np.random.randint(1,10, size =(10,))
print(a)
splitted_array = np.array_split(a,3)
print(splitted_array)

# split -> equal division

[9 4 3 4 6 1 5 3 8 4]
[array([9, 4, 3, 4], dtype=int32), array([6, 1, 5], dtype=int32), array([3, 8, 4], dtype=int32)]


# arithmatic  operator and mathmatical function

In [29]:
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add=x+y
print(add)

[12 23 34 45]
