# ndarray

In [1]:
arr = [1,2,3]

print(arr*5)

arr = [x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr1 = arr1*5
print(arr1)

[ 5 10 15]


# Ndarray

In [9]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5])

print(type(arr1))
print(arr1.ndim)

# 2D array
arr2 = np.array([[1,2,3], # Row1
                [4,5,6]   # Row2
                ])
print(arr2.ndim)

# 3D array
arr3 = np.array([
        # 1st floor
        [[1,2,3], # Row1
        [4,5,6] ],   # Row2

    
        # 2nd floor 
        [[1,2,3], # Row1
        [4,5,6] ]   # Row2
    
])

print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


## Array attributes

In [10]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# data type

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12


# nd array data type

In [11]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.3])

print(arr.dtype)



int64
float64


In [14]:
arr = np.array([1,2,3.3])
# upcasting
print(arr.dtype)
# upcasting to string
arr = np.array([1,2,3.3,'3'])
print(arr.dtype)

float64
<U32


## selecting a data type for an array

In [18]:
arr = np.array([1,2,3])
print(arr.dtype)
arr = arr.astype(np.int32)
print(arr.dtype)
print(arr)

int64
int32
[1 2 3]


# nd array creating from existing data

In [24]:
# List
lst = [10,20,30,40,40.5]
arr = np.array(lst,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

matrix = [[1,2,3], # Row1
         [4,5,6]   # Row2
                ]
arr = np.array(matrix,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
(2, 3)
2


In [25]:
# tuple
tpl=(10,20,30)
arr = np.array(tpl,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int32
(3,)
1


In [30]:
# set

st = {1,2,3}
arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1
