# ndarray

In [1]:
arr = [1,2,3]

print(arr*5)

arr = [x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr1 = arr1*5
print(arr1)

[ 5 10 15]


# Ndarray

In [3]:
import numpy as np

# 1D array
arr1 = np.array([1,2,3,4,5])

print(type(arr1))
print(arr1.ndim)

# 2D array
arr2 = np.array([[1,2,3], # Row1
                [4,5,6]   # Row2
                ])
print(arr2.ndim)

# 3D array
arr3 = np.array([
        # 1st floor
        [[1,2,3], # Row1
        [4,5,6] ],   # Row2

    
        # 2nd floor 
        [[1,2,3], # Row1
        [4,5,6] ]   # Row2
    
])

print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


## Array attributes

In [4]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# data type

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12


# nd array data type

In [5]:
arr = np.array([1,2,3])

print(arr.dtype)

arr = np.array([1.5,2.4,3.3])

print(arr.dtype)



int64
float64


In [6]:
arr = np.array([1,2,3.3])
# upcasting
print(arr.dtype)
# upcasting to string
arr = np.array([1,2,3.3,'3'])
print(arr.dtype)

float64
<U32


## selecting a data type for an array

In [7]:
arr = np.array([1,2,3])
print(arr.dtype)
arr = arr.astype(np.int32)
print(arr.dtype)
print(arr)

int64
int32
[1 2 3]


# nd array creating from existing data

In [8]:
# List
lst = [10,20,30,40,40.5]
arr = np.array(lst,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

matrix = [[1,2,3], # Row1
         [4,5,6]   # Row2
                ]
arr = np.array(matrix,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
(2, 3)
2


In [9]:
# tuple
tpl=(10,20,30)
arr = np.array(tpl,dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int32
(3,)
1


In [10]:
# set

st = {1,2,3}
arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [11]:
# dictonary
dc = {'a' : 10,'b' : 20, 'c':30}

keys = dc.keys()
values = dc.values()
items = dc.items()
print(items)

# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [12]:
# values to ndarray
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
3


In [13]:
# items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# array creation of random value

In [19]:
## np.random.rand(shape)

arr = np.random.rand(2,3) # 0 -> 1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.16598466 0.72998926 0.95401635]
 [0.43707434 0.1110849  0.46598209]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [20]:
## np.random.randint(start,end,shape)

arr = np.random.randint(1,10,(10,10)) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[4 2 6 8 4 3 4 4 5 6]
 [8 9 5 7 9 7 7 7 1 2]
 [7 9 6 8 3 3 9 3 5 6]
 [6 9 6 8 7 7 9 8 9 4]
 [4 3 9 3 5 3 9 5 9 8]
 [4 7 5 6 3 5 3 6 2 6]
 [6 3 1 8 5 5 3 7 6 7]
 [2 9 7 6 2 5 5 2 2 8]
 [6 6 5 2 2 4 4 1 2 9]
 [4 3 8 9 1 8 6 8 4 6]]
<class 'numpy.ndarray'>
int32
(10, 10)
2
100


In [21]:
## np.random.uniform(start,end,shape)

arr = np.random.uniform(50,100,(2,3)) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[77.40612017 53.39533373 61.96881363]
 [84.6580769  55.47349588 59.00881824]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6
